### PR TITLE
.datepicker calls renamed to .bdatepicker

### PR DESCRIPTION
**Pull request by Paaashka**
Seems like it should be done, and it fixes some "undefined" errors in console.

### CODE REVIEW

**Comment by tonydspaniard** [comment]
That will caus conflicts with jquery datepicker .  Other options?

**Comment by Paaashka** [comment]
I'm not sure, but i think it will not break anything, because bootstrap-datepicker in now registered as "bdatepicker" (at least in bs3 branch), and there is not "datepicker" at all. Can you please explain, why this changes will cause problems?

**Comment by tonydspaniard** [comment]
oh sorry... I was looking it differently the other way around on my phone! :)

**Comment by Paaashka** [comment]
Hi again. Is there still some problems with PR or there is some other reason for not merging it in? :)

**Comment by tonydspaniard** [comment]
Whats just a matter of having some free time (that I still do not have). Thanks @Paaashka

**Pull request merged**
